// PLNTD menu data — sourced from the design system
// Nutrition values are estimates based on ingredients — replace with measured numbers when you have them.

window.MENU = [
  {
    id: 'smoothies',
    title: 'Smoothies',
    eyebrow: '',
    blurb: 'Thick, fruit-forward blends. All smoothies include coconut water.',
    items: [
      { name: 'Green Glow',         ingr: 'apple, spinach, avocado, broccoli, lemon, coconut water', price: 6.50, color: '#3E7A1E', img: 'assets/drinks/smoothie-green-glow.png?v=6',
        allergens: ['Coconut'], nutrition: { kj: 720, kcal: 172, fat: 8, satFat: 1.2, carbs: 18, sugars: 12, fibre: 5, protein: 3, sodium: 25 } },
      { name: 'Green Machine',      ingr: 'kale, spinach, cucumber, apple, ginger, lemon, coconut water', price: 6.50, color: '#3E7A1E', img: 'assets/drinks/smoothie-green-machine.png?v=6',
        allergens: ['Coconut'], nutrition: { kj: 380, kcal: 90, fat: 0.6, satFat: 0.1, carbs: 22, sugars: 14, fibre: 4, protein: 2, sodium: 35 } },
      { name: 'Pineapple Sunrise',  ingr: 'pineapple, banana, apple, coconut water', price: 6.50, color: '#DF9A00', img: 'assets/drinks/smoothie-pineapple-sunrise.png?v=6',
        allergens: ['Coconut'], nutrition: { kj: 760, kcal: 180, fat: 0.6, satFat: 0.1, carbs: 44, sugars: 32, fibre: 4, protein: 2, sodium: 10 } },
      { name: 'Blueberry Breeze',   ingr: 'blueberries, banana, almond milk', price: 6.50, color: '#2E0096', img: 'assets/drinks/smoothie-blueberry-breeze.png?v=6',
        allergens: ['Tree nuts (almond)'], nutrition: { kj: 840, kcal: 200, fat: 4, satFat: 0.3, carbs: 39, sugars: 28, fibre: 4, protein: 3, sodium: 70 } },
      { name: 'Strawberry Delight', ingr: 'strawberries, apple, coconut water', price: 6.50, color: '#C1002F', img: 'assets/drinks/smoothie-strawberry-delight.png?v=6',
        allergens: ['Coconut'], nutrition: { kj: 460, kcal: 110, fat: 0.4, satFat: 0.1, carbs: 27, sugars: 20, fibre: 5, protein: 1, sodium: 8 } },
      { name: 'Berry Blast',        ingr: 'strawberries, banana, apple, coconut water', price: 6.50, color: '#CA0039', img: 'assets/drinks/smoothie-berry-blast.png?v=6',
        allergens: ['Coconut'], nutrition: { kj: 670, kcal: 160, fat: 0.5, satFat: 0.1, carbs: 39, sugars: 27, fibre: 5, protein: 2, sodium: 8 } },
    ],
  },
  {
    id: 'juices',
    title: 'Fresh Juices',
    eyebrow: '',
    blurb: 'Pressed in-store every morning. Nothing from concentrate.',
    items: [
      { name: 'Garden Green',      ingr: 'cucumber, celery, kale', price: 6.00, color: '#3E7A1E', img: 'assets/drinks/juice-garden-green.png?v=6',
        allergens: [], nutrition: { kj: 210, kcal: 50, fat: 0.3, satFat: 0, carbs: 11, sugars: 6, fibre: 2, protein: 2, sodium: 30 }, noAddedSugar: true },
      { name: 'Carrot Glow',       ingr: 'carrot, apple, ginger', price: 6.00, color: '#CA3D00', img: 'assets/drinks/juice-carrot-glow.png?v=9',
        allergens: [], nutrition: { kj: 460, kcal: 110, fat: 0.3, satFat: 0, carbs: 26, sugars: 20, fibre: 3, protein: 1, sodium: 35 }, noAddedSugar: true },
      { name: 'Sunrise Carrot',    ingr: 'carrot, orange, lemon', price: 6.00, color: '#CA3D00', img: 'assets/drinks/juice-sunrise-carrot.png?v=9',
        allergens: [], nutrition: { kj: 550, kcal: 130, fat: 0.3, satFat: 0, carbs: 31, sugars: 25, fibre: 4, protein: 2, sodium: 30 }, noAddedSugar: true },
      { name: 'Daily Cleanse',     ingr: 'apple, carrot, ginger', price: 6.00, color: '#3E7A1E', img: 'assets/drinks/juice-daily-cleanse.png?v=7',
        allergens: [], nutrition: { kj: 630, kcal: 150, fat: 0.4, satFat: 0, carbs: 37, sugars: 30, fibre: 4, protein: 1, sodium: 12 }, noAddedSugar: true },
      { name: 'Citrus Refresher',  ingr: 'apple, mint, ginger, lemon', price: 6.00, color: '#DF9A00', img: 'assets/drinks/juice-citrus-refresher.png?v=6',
        allergens: [], nutrition: { kj: 590, kcal: 140, fat: 0.3, satFat: 0, carbs: 35, sugars: 28, fibre: 3, protein: 0, sodium: 5 }, noAddedSugar: true },
      { name: 'Apple Zing',        ingr: 'apple, mint, ginger', price: 6.00, color: '#3E7A1E', img: 'assets/drinks/juice-apple-zing.png?v=6',
        allergens: [], nutrition: { kj: 590, kcal: 140, fat: 0.3, satFat: 0, carbs: 35, sugars: 28, fibre: 3, protein: 0, sodium: 5 }, noAddedSugar: true },
      { name: 'Citrus Boost',      ingr: 'orange, lemon, carrot', price: 6.00, color: '#DF9A00', img: 'assets/drinks/juice-citrus-boost.png?v=10',
        allergens: [], nutrition: { kj: 550, kcal: 130, fat: 0.3, satFat: 0, carbs: 31, sugars: 25, fibre: 4, protein: 2, sodium: 25 }, noAddedSugar: true },
      { name: 'Vitamin C Blast',   ingr: 'orange, pineapple, lemon', price: 6.00, color: '#DF9A00', img: 'assets/drinks/juice-vitamin-c-blast.png?v=6',
        allergens: [], nutrition: { kj: 710, kcal: 170, fat: 0.4, satFat: 0, carbs: 41, sugars: 35, fibre: 4, protein: 2, sodium: 8 }, noAddedSugar: true },
      { name: 'Berry Fresh',       ingr: 'strawberries, apple, lemon', price: 6.00, color: '#C1002F', img: 'assets/drinks/juice-berry-fresh.png?v=6',
        allergens: [], nutrition: { kj: 420, kcal: 100, fat: 0.3, satFat: 0, carbs: 24, sugars: 18, fibre: 3, protein: 1, sodium: 5 }, noAddedSugar: true },
    ],
  },
  {
    id: 'sandwiches',
    title: 'Sandwiches',
    eyebrow: '',
    blurb: 'Made fresh to order on the day.',
    items: [
      { name: 'Chicken Mayo',      ingr: 'chicken breast, red onion, peppers, house mayo and chilli · served in focaccia bread',       price: 6.00, color: '#C9A227', img: 'assets/drinks/sandwich-chicken-mayo.png?v=2',
        allergens: ['Egg', 'Gluten', 'Mustard', 'Sesame'], nutrition: { kj: 2900, kcal: 700, fat: 42, satFat: 7, carbs: 46, sugars: 5, fibre: 3, protein: 37, sodium: 800 } },
      { name: 'Tuna Crunch',       ingr: 'tuna, red onion, mixed peppers, sweet corn, house mayo and chilli · served in focaccia bread', price: 6.00, color: '#D98B2B', img: 'assets/drinks/sandwich-tuna-crunch.png?v=2',
        allergens: ['Fish', 'Egg', 'Gluten', 'Mustard', 'Sesame'], nutrition: { kj: 2750, kcal: 660, fat: 37, satFat: 6, carbs: 50, sugars: 7, fibre: 3, protein: 27, sodium: 950 } },
      { name: 'Steak and Peppers', ingr: 'steak, mixed pepper, onion, house marinade · served in focaccia bread',                       price: 6.50, color: '#7A2E1E', img: 'assets/drinks/sandwich-steak-peppers.png?v=2',
        allergens: ['Gluten', 'Mustard', 'Soya'], nutrition: { kj: 1900, kcal: 455, fat: 13, satFat: 5, carbs: 47, sugars: 5, fibre: 3, protein: 32, sodium: 690 } },
    ],
  },
  {
    id: 'coffee',
    title: 'Specialty Coffee',
    eyebrow: '',
    blurb: 'Single-origin beans, oat or almond milk on request. Iced and signature drinks served over ice.',
    items: [
      { name: 'Espresso',    ingr: 'double shot',                price: 3.50, color: '#3D2817', img: 'assets/drinks/coffee-espresso.png?v=4',
        allergens: [], nutrition: { kj: 20, kcal: 5, fat: 0, satFat: 0, carbs: 1, sugars: 0, fibre: 0, protein: 0, sodium: 5 } },
      { name: 'Americano',   ingr: 'espresso, hot water',        price: 3.50, color: '#3D2817', img: 'assets/drinks/coffee-americano.png?v=4',
        allergens: [], nutrition: { kj: 20, kcal: 5, fat: 0, satFat: 0, carbs: 1, sugars: 0, fibre: 0, protein: 0, sodium: 8 } },
      { name: 'Cortado',     ingr: 'espresso, warm milk',        price: 3.50, color: '#A07856', img: 'assets/drinks/coffee-cortado.png?v=16',
        allergens: ['Milk'], nutrition: { kj: 210, kcal: 50, fat: 2.5, satFat: 1.5, carbs: 4, sugars: 4, fibre: 0, protein: 3, sodium: 40 } },
      { name: 'Flat White',  ingr: 'espresso, steamed milk', price: 3.50, color: '#B89373', img: 'assets/drinks/coffee-flat-white.png?v=11',
        allergens: ['Milk'], nutrition: { kj: 460, kcal: 110, fat: 5, satFat: 3, carbs: 9, sugars: 9, fibre: 0, protein: 6, sodium: 85 } },
      { name: 'Cappuccino',  ingr: 'espresso, steamed milk, foam', price: 3.90, color: '#C9A98A', img: 'assets/drinks/coffee-cappuccino.png?v=4',
        allergens: ['Milk'], nutrition: { kj: 380, kcal: 90, fat: 4, satFat: 2.5, carbs: 7, sugars: 7, fibre: 0, protein: 5, sodium: 70 } },
      { name: 'Latte',       ingr: 'espresso, steamed milk',     price: 3.90, color: '#BE9772', img: 'assets/drinks/coffee-latte.png?v=13',
        allergens: ['Milk'], nutrition: { kj: 550, kcal: 130, fat: 6, satFat: 3.5, carbs: 11, sugars: 11, fibre: 0, protein: 7, sodium: 100 } },
      { name: 'Spanish Latte', ingr: 'espresso, condensed milk', price: 3.90, color: '#B98A5E', img: 'assets/drinks/coffee-spanish-latte.png',
        allergens: ['Milk'], nutrition: { kj: 270, kcal: 65, fat: 1.5, satFat: 1, carbs: 11, sugars: 11, fibre: 0, protein: 2, sodium: 25 } },
      { name: 'Iced Americano',     ingr: 'espresso, cold water, ice',     price: 4.00, color: '#3D2817', img: 'assets/drinks/coffee-iced-americano.png',
        allergens: [], nutrition: { kj: 15, kcal: 3, fat: 0, satFat: 0, carbs: 0, sugars: 0, fibre: 0, protein: 0, sodium: 5 } },
      { name: 'Iced Latte',         ingr: 'espresso, cold milk, ice',      price: 4.50, color: '#BE9772', img: 'assets/drinks/coffee-iced-coffee.png?v=4',
        allergens: ['Milk'], nutrition: { kj: 350, kcal: 85, fat: 4, satFat: 2.5, carbs: 10, sugars: 10, fibre: 0, protein: 8, sodium: 90 } },
      { name: 'Iced Matcha Latte',  ingr: 'matcha, milk, ice',        price: 4.50, color: '#5E8A2D', img: 'assets/drinks/coffee-iced-matcha.png',
        allergens: ['Milk'], nutrition: { kj: 350, kcal: 84, fat: 3.5, satFat: 2, carbs: 10, sugars: 9, fibre: 0, protein: 8, sodium: 85 } },
      { name: 'Iced Spanish Latte', ingr: 'espresso, condensed milk, ice', price: 4.50, color: '#A07856', img: 'assets/drinks/coffee-iced-spanish-latte.png',
        allergens: ['Milk'], nutrition: { kj: 400, kcal: 95, fat: 2.5, satFat: 1.5, carbs: 17, sugars: 17, fibre: 0, protein: 2.5, sodium: 40 } },
    ],
  },
  {
    id: 'tea',
    title: 'Tea',
    eyebrow: '',
    blurb: 'Brewed by the cup. Steeped to order.',
    items: [
      { name: 'English Tea', ingr: 'black tea blend',  price: 2.75, color: '#9C3D1F', img: 'assets/drinks/coffee-english-tea.png?v=6',
        allergens: [], nutrition: { kj: 10, kcal: 2, fat: 0, satFat: 0, carbs: 0, sugars: 0, fibre: 0, protein: 0, sodium: 8 } },
      { name: 'Green Tea',   ingr: 'loose-leaf sencha', price: 2.75, color: '#7A8A2D', img: 'assets/drinks/coffee-green-tea.png?v=6',
        allergens: [], nutrition: { kj: 5, kcal: 1, fat: 0, satFat: 0, carbs: 0, sugars: 0, fibre: 0, protein: 0, sodium: 5 } },
      { name: 'Matcha Latte', ingr: 'ceremonial matcha, hot water', price: 3.50, color: '#5E8A2D', img: 'assets/drinks/coffee-matcha.png?v=2',
        allergens: [], nutrition: { kj: 40, kcal: 10, fat: 0, satFat: 0, carbs: 1, sugars: 0.5, fibre: 0, protein: 1, sodium: 5 } },
    ],
  },
  {
    id: 'bakes',
    title: 'Artisan Bakes',
    eyebrow: '',
    blurb: 'Freshly baked. Best enjoyed with a coffee.',
    items: [
      // NOTE: prices, ingredients and nutrition below are placeholders — replace with real values.
      { name: 'Plain Croissant',   ingr: 'butter, flour', price: 2.50, color: '#C68A3E', img: 'assets/drinks/bake-plain-croissant.png',
        allergens: ['Gluten', 'Milk', 'Egg'], nutrition: { kj: 1130, kcal: 270, fat: 14, satFat: 8, carbs: 30, sugars: 6, fibre: 1.5, protein: 5, sodium: 300 } },
      { name: 'Almond Croissant',  ingr: 'almond frangipane, flaked almonds', price: 3.20, color: '#B98A5E', img: 'assets/drinks/bake-almond-croissant.png',
        allergens: ['Gluten', 'Milk', 'Egg', 'Tree nuts (almond)'], nutrition: { kj: 1760, kcal: 420, fat: 24, satFat: 10, carbs: 42, sugars: 18, fibre: 3, protein: 9, sodium: 320 } },
      { name: 'Blueberry Muffin',  ingr: 'blueberries, vanilla', price: 2.80, color: '#3E5AA0', img: 'assets/drinks/bake-blueberry-muffin.png',
        allergens: ['Gluten', 'Milk', 'Egg'], nutrition: { kj: 1590, kcal: 380, fat: 16, satFat: 3, carbs: 54, sugars: 30, fibre: 2, protein: 5, sodium: 350 } },
      { name: 'Cinnamon Roll',     ingr: 'cinnamon, brown sugar, icing', price: 3.20, color: '#8B5A2B', img: 'assets/drinks/bake-cinnamon-roll.png',
        allergens: ['Gluten', 'Milk', 'Egg'], nutrition: { kj: 1510, kcal: 360, fat: 12, satFat: 5, carbs: 56, sugars: 26, fibre: 2, protein: 6, sodium: 340 } },
    ],
  },
];

// Store info — placeholders, ask user to confirm
window.STORE = {
  name: 'Leyton',
  fullName: 'PLNTD — Leyton',
  address: '144 High Road Leyton',
  addressLine2: 'London E15 2BX',
  phone: '020 7000 0000',
  hours: [
    { day: 'Monday',    open: '07:00', close: '19:00' },
    { day: 'Tuesday',   open: '07:00', close: '19:00' },
    { day: 'Wednesday', open: '07:00', close: '19:00' },
    { day: 'Thursday',  open: '07:00', close: '19:00' },
    { day: 'Friday',    open: '07:00', close: '19:00' },
    { day: 'Saturday',  open: '09:00', close: '19:00' },
    { day: 'Sunday',    open: '09:00', close: '17:00' },
  ],
  todayIndex: new Date().getDay() === 0 ? 6 : new Date().getDay() - 1, // monday-first
  features: ['Pickup', 'Dine-in', 'Wi-Fi'],
};

window.OTHER_STORES = [
  { name: 'Shoreditch',  area: 'Old Street · 1.8 mi' },
  { name: 'Borough',     area: 'London Bridge · 2.1 mi' },
  { name: 'Marylebone',  area: 'Baker Street · 1.4 mi' },
];
